# Google Cloud Build configuration for automatic deployments
# This file enables CI/CD integration with Cloud Build

steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/everybodys-news-app:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/everybodys-news-app:latest'
      - '.'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/everybodys-news-app:$COMMIT_SHA'

  # Push the latest tag
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/everybodys-news-app:latest'

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'everybodys-news-app'
      - '--image'
      - 'gcr.io/$PROJECT_ID/everybodys-news-app:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
      - '--port'
      - '8080'

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/everybodys-news-app:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/everybodys-news-app:latest'

# Timeout for the entire build
timeout: 1200s

# Use a larger machine for faster builds
options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
